name: Pull Data and Write Secret

on:
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest
    if: github.actor == 'CaoThanhNammm' || github.actor == 'ducvui2003' || github.actor == '21130449-NguyenKhaiNam'

    steps:
        - run: echo "${{ secrets.CREDENTIALS }}" > src/main/resources/credential.json